INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CG-12520', 'Claire Gute', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DV-13045', 'Darrin Van Huff', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SO-20335', 'Sean O''Donnell', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BH-11710', 'Brosina Hoffman', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AA-10480', 'Andrew Allen', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('IM-15070', 'Irene Maddox', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HP-14815', 'Harold Pawlan', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PK-19075', 'Pete Kriz', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AG-10270', 'Alejandro Grove', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ZD-21925', 'Zuschuss Donatelli', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KB-16585', 'Ken Black', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SF-20065', 'Sandra Flanagan', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EB-13870', 'Emily Burns', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EH-13945', 'Eric Hoffmann', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TB-21520', 'Tracy Blumstein', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MA-17560', 'Matt Abelman', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GH-14485', 'Gene Hale', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SN-20710', 'Steve Nguyen', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LC-16930', 'Linda Cazamias', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RA-19885', 'Ruben Ausman', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ES-14080', 'Erin Smith', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ON-18715', 'Odella Nelson', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PO-18865', 'Patrick O''Donnell', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LH-16900', 'Lena Hernandez', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DP-13000', 'Darren Powers', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JM-15265', 'Janet Molinari', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TB-21055', 'Ted Butterfield', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KM-16720', 'Kunst Miller', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PS-18970', 'Paul Stevenson', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BS-11590', 'Brendan Sweed', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KD-16270', 'Karen Daniels', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HM-14980', 'Henry MacAllister', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JE-15745', 'Joel Eaton', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KB-16600', 'Ken Brennan', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20770', 'Stewart Carmichael', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DN-13690', 'Duane Noonan', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JC-16105', 'Julie Creighton', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CS-12400', 'Christopher Schild', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PG-18895', 'Paul Gonzalez', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GM-14455', 'Gary Mitchum', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JS-15685', 'Jim Sink', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KB-16315', 'Karl Braun', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RB-19705', 'Roger Barcio', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PN-18775', 'Parhena Norris', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KD-16345', 'Katherine Ducich', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ER-13855', 'Elpida Rittenbach', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RB-19465', 'Rick Bensley', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GZ-14470', 'Gary Zandusky', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LC-16870', 'Lena Cacioppo', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JM-15250', 'Janet Martin', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PA-19060', 'Pete Armstrong', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CV-12805', 'Cynthia Voltz', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CL-12565', 'Clay Ludtke', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RC-19960', 'Ryan Crowe', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DK-13090', 'Dave Kipp', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GG-14650', 'Greg Guthrie', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20725', 'Steven Cartwright', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AD-10180', 'Alan Dominguez', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PF-19165', 'Philip Fox', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TS-21610', 'Troy Staebel', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LS-16975', 'Lindsay Shagiari', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DW-13585', 'Dorothy Wardle', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LC-16885', 'Lena Creighton', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JD-15895', 'Jonathan Doherty', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SH-19975', 'Sally Hughsby', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SG-20080', 'Sandra Glassco', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HA-14920', 'Helen Andreada', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MG-17680', 'Maureen Gastineau', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JE-16165', 'Justin Ellison', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TW-21025', 'Tamara Willingham', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SP-20650', 'Stephanie Phelps', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NK-18490', 'Neil Knudson', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DB-13060', 'Dave Brooks', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NP-18670', 'Nora Paige', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TT-21070', 'Ted Trevino', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EM-13960', 'Eric Murdock', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RD-19900', 'Ruben Dartt', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MJ-17740', 'Max Jones', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BM-11140', 'Becky Martin', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CS-12130', 'Chad Sievert', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JB-15400', 'Jennifer Braxton', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SJ-20500', 'Shirley Jackson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JK-15640', 'Jim Kriz', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DK-13150', 'David Kendrick', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RM-19675', 'Robert Marley', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SK-19990', 'Sally Knutson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('FM-14290', 'Frank Merwin', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AM-10360', 'Alice McCarthy', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MP-17470', 'Mark Packer', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MZ-17515', 'Mary Zewe', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CB-12025', 'Cassandra Brandow', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('VM-21685', 'Valerie Mitchum', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('FH-14365', 'Fred Hopkins', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MB-17305', 'Maria Bertelson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BS-11755', 'Bruce Stewart', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LC-17140', 'Logan Currie', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HK-14890', 'Heather Kirkland', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LE-16810', 'Laurel Elliston', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JH-15985', 'Joseph Holt', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MS-17980', 'Michael Stewart', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('VW-21775', 'Victoria Wilson', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JH-15910', 'Jonathan Howell', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JB-15925', 'Joni Blumstein', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DS-13180', 'David Smith', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('VD-21670', 'Valerie Dominguez', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EA-14035', 'Erin Ashbrook', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DB-13120', 'David Bremer', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KL-16645', 'Ken Lonsdale', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DW-13480', 'Dianna Wilson', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LH-17155', 'Logan Haushalter', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KC-16540', 'Kelly Collister', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DL-13315', 'Delfina Latchford', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DR-12880', 'Dan Reichenbach', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CC-12670', 'Craig Carreira', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('Dl-13600', 'Dorris liebe', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SB-20290', 'Sean Braxton', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RC-19825', 'Roy Collins', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AH-10210', 'Alan Hwang', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CB-12535', 'Claudia Bergmann', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CA-12310', 'Christine Abelman', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KH-16690', 'Kristen Hastings', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BB-10990', 'Barry Blumstein', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AG-10495', 'Andrew Gjertsen', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JO-15280', 'Jas O''Carroll', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AH-10195', 'Alan Haines', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NZ-18565', 'Nick Zandusky', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KL-16555', 'Kelly Lampkin', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AS-10225', 'Alan Schoenberger', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CR-12625', 'Corey Roper', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SH-20395', 'Shahid Hopkins', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BP-11185', 'Ben Peterman', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TS-21205', 'Thomas Seio', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AG-10525', 'Andy Gerbode', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SP-20860', 'Sung Pak', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NM-18445', 'Nathan Mautz', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('FA-14230', 'Frank Atkinson', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GK-14620', 'Grace Kelly', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DJ-13510', 'Don Jones', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PO-18850', 'Patrick O''Brill', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JL-15850', 'John Lucas', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DB-13615', 'Doug Bickford', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AC-10420', 'Alyssa Crouse', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CC-12550', 'Clay Cheatham', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TD-20995', 'Tamara Dahlen', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AB-10060', 'Adam Bellavance', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JL-15505', 'Jeremy Lonsdale', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('VB-21745', 'Victoria Brennan', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KW-16435', 'Katrina Willman', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JD-16060', 'Julia Dunbar', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MK-17905', 'Michael Kennedy', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GT-14755', 'Guy Thornton', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AG-10900', 'Arthur Gainer', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MM-18280', 'Muhammed MacIntyre', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AR-10405', 'Allen Rosenblatt', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RA-19915', 'Russell Applegate', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AS-10285', 'Alejandro Savely', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LA-16780', 'Laura Armstrong', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DO-13435', 'Denny Ordway', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DK-13225', 'Dean Katz', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NG-18430', 'Nathan Gelder', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MV-18190', 'Mike Vittorini', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JG-15115', 'Jack Garza', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BP-11095', 'Bart Pistole', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('VP-21730', 'Victor Preis', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SS-20140', 'Saphhira Shifley', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AG-10675', 'Anna Gayman', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LF-17185', 'Luke Foster', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RF-19840', 'Roy Französisch', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KH-16510', 'Keith Herrera', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KC-16675', 'Kimberly Carter', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CJ-12010', 'Caroline Jumper', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PB-19150', 'Philip Brown', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MP-17965', 'Michael Paige', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NF-18385', 'Natalie Fritzler', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SD-20485', 'Shirley Daniels', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KH-16630', 'Ken Heidel', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RB-19795', 'Ross Baird', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MK-18160', 'Mike Kennedy', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PO-19180', 'Philisse Overcash', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BB-11545', 'Brenda Bowman', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TB-21595', 'Troy Blackwell', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RB-19360', 'Raymond Buch', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EB-13705', 'Ed Braxton', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20095', 'Sanjit Chand', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TN-21040', 'Tanja Norvell', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JS-15940', 'Joni Sundaresam', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MH-17785', 'Maya Herman', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JP-15520', 'Jeremy Pistek', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JE-15475', 'Jeremy Ellison', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JG-15805', 'John Grady', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('XP-21865', 'Xylona Preis', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EM-14065', 'Erin Mull', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MT-18070', 'Michelle Tran', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SA-20830', 'Sue Ann Reed', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CW-11905', 'Carl Weiss', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AJ-10960', 'Astrea Jones', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SS-20590', 'Sonia Sunley', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RO-19780', 'Rose O''Brian', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MD-17350', 'Maribeth Dona', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MY-17380', 'Maribeth Yedwab', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CM-12385', 'Christopher Martinez', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LS-17245', 'Lynn Smith', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BN-11515', 'Bradley Nguyen', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DB-13210', 'Dean Braden', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MC-17605', 'Matt Connell', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BD-11605', 'Brian Dahlen', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PH-18790', 'Patricia Hirasaki', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MG-18145', 'Mike Gockenbach', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KB-16240', 'Karen Bern', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JC-15340', 'Jasper Cacioppo', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RL-19615', 'Rob Lucas', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AA-10375', 'Allen Armold', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EP-13915', 'Emily Phan', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DK-12985', 'Darren Koutras', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BD-11500', 'Bradley Drucker', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LM-17065', 'Liz MacKendrick', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AS-10135', 'Adrian Shami', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BD-11320', 'Bill Donatelli', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GT-14710', 'Greg Tran', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AJ-10945', 'Ashley Jarboe', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('OT-18730', 'Olvera Toch', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LP-17080', 'Liz Pelletier', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CA-12775', 'Cynthia Arntzen', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JF-15490', 'Jeremy Farry', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('FP-14320', 'Frank Preis', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EB-13840', 'Ellis Ballard', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JF-15415', 'Jennifer Ferguson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SF-20200', 'Sarah Foster', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TG-21640', 'Trudy Glocke', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CS-11950', 'Carlos Soltero', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CC-12145', 'Charles Crestani', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DV-13465', 'Dianna Vittorini', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BD-11725', 'Bruce Degenhardt', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ZC-21910', 'Zuschuss Carroll', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MS-17830', 'Melanie Seite', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LR-16915', 'Lena Radford', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TP-21130', 'Theone Pippenger', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CK-12205', 'Chloris Kastensmidt', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AS-10240', 'Alan Shonely', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AR-10510', 'Andrew Roberts', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NB-18655', 'Nona Balk', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GD-14590', 'Giulietta Dortch', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CK-12595', 'Clytie Kelty', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NG-18355', 'Nat Gilpin', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CA-12265', 'Christina Anderson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SF-20965', 'Sylvia Foulston', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MO-17800', 'Meg O''Connel', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AT-10735', 'Annie Thurman', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('FM-14380', 'Fred McMath', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DJ-13420', 'Denny Joy', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ME-17725', 'Max Engle', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JD-16150', 'Justin Deggeller', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JL-15835', 'John Lee', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20305', 'Sean Christensen', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CC-12430', 'Chuck Clark', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AR-10825', 'Anthony Rawles', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SR-20740', 'Steven Roelle', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CR-12730', 'Craig Reiter', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EH-14125', 'Eugene Hildebrand', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SP-20545', 'Sibella Parks', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TH-21235', 'Tiffany House', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RP-19390', 'Resi Pölking', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RB-19570', 'Rob Beeghly', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CD-11980', 'Carol Darley', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DJ-13630', 'Doug Jacobs', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GT-14635', 'Grant Thornton', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MC-17845', 'Michael Chen', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RA-19285', 'Ralph Arnett', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NP-18325', 'Naresj Patel', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AB-10165', 'Alan Barnes', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JO-15550', 'Jesus Ocampo', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JK-15370', 'Jay Kimmel', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BN-11470', 'Brad Norvell', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DP-13165', 'David Philippe', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TH-21550', 'Tracy Hopkins', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AP-10915', 'Arthur Prichep', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RS-19765', 'Roland Schwarz', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SV-20365', 'Seth Vernon', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CK-12325', 'Christine Kargatis', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RD-19810', 'Ross DeVincentis', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MR-17545', 'Mathew Reese', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20695', 'Steve Chapman', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JF-15355', 'Jay Fein', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EG-13900', 'Emily Grady', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DS-13030', 'Darrin Sayre', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PO-19195', 'Phillina Ober', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SS-20875', 'Sung Shariari', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PB-19105', 'Peter Bühler', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RF-19735', 'Roland Fjeld', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('YC-21895', 'Yoseph Carroll', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DC-13285', 'Debra Catini', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CP-12340', 'Christine Phan', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BF-11020', 'Barry Französisch', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LH-17020', 'Lisa Hazard', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CS-12250', 'Chris Selesnick', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AJ-10795', 'Anthony Johnson', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BV-11245', 'Benjamin Venier', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DL-12865', 'Dan Lawera', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BM-11785', 'Bryan Mills', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LT-17110', 'Liz Thompson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JK-15730', 'Joe Kamberova', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ES-14020', 'Erica Smith', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RH-19495', 'Rick Hansen', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CD-11920', 'Carlos Daly', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HW-14935', 'Helen Wasserman', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MC-18130', 'Mike Caudle', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GM-14440', 'Gary McGarr', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PJ-19015', 'Pauline Johnson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BW-11110', 'Bart Watters', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TR-21325', 'Toby Ritter', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PG-18820', 'Patrick Gardner', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JL-15175', 'James Lanier', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BM-11650', 'Brian Moss', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EM-14095', 'Eudokia Martin', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AF-10885', 'Art Foster', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GA-14725', 'Guy Armstrong', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CK-12760', 'Cyma Kinney', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DP-13105', 'Dave Poirier', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BK-11260', 'Berenike Kampe', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SJ-20125', 'Sanjit Jacobs', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CM-12445', 'Chuck Magee', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AJ-10780', 'Anthony Jacobs', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LS-16945', 'Linda Southworth', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GP-14740', 'Guy Phonely', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PK-18910', 'Paul Knutson', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SM-20005', 'Sally Matthias', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AG-10765', 'Anthony Garverick', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PM-19135', 'Peter McVee', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LL-16840', 'Lauren Leatherbury', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JS-15595', 'Jill Stevenson', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EL-13735', 'Ed Ludwig', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PC-18745', 'Pamela Coakley', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HL-15040', 'Hunter Lopez', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MS-17365', 'Maribeth Schnelling', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GB-14530', 'George Bell', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JR-16210', 'Justin Ritter', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BE-11335', 'Bill Eplett', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20050', 'Sample Company A', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RW-19630', 'Rob Williams', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SE-20110', 'Sanjit Engle', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AH-10075', 'Adam Hart', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JM-15535', 'Jessica Myrick', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JJ-15760', 'Joel Jenkins', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RK-19300', 'Ralph Kennedy', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CG-12040', 'Catherine Glotzbach', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RP-19270', 'Rachel Payne', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KC-16255', 'Karen Carlisle', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KH-16360', 'Katherine Hughes', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GH-14665', 'Greg Hansen', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SW-20275', 'Scott Williamson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JA-15970', 'Joseph Airdo', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DL-12925', 'Daniel Lacy', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LW-16990', 'Lindsay Williams', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TB-21190', 'Thomas Brumley', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BS-11800', 'Bryan Spruell', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RW-19690', 'Robert Waldorf', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TZ-21580', 'Tracy Zic', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AS-10630', 'Ann Steele', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TS-21340', 'Toby Swindell', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SL-20155', 'Sara Luxemburg', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MW-18235', 'Mitch Willingham', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RD-19585', 'Rob Dowd', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RA-19945', 'Ryan Akin', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MT-17815', 'Meg Tillman', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('VG-21790', 'Vivek Gonzalez', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JS-15880', 'John Stevenson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KM-16225', 'Kalyca Meade', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HR-14770', 'Hallie Redmond', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DE-13255', 'Deanra Eno', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AG-10390', 'Allen Goldenen', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JJ-15445', 'Jennifer Jackson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JH-15430', 'Jennifer Halladay', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RD-19660', 'Robert Dilbeck', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MO-17500', 'Mary O''Rourke', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NS-18640', 'Noel Staavos', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DG-13300', 'Deirdre Greer', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NF-18595', 'Nicole Fjeld', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MG-17650', 'Matthew Grinstein', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TS-21160', 'Theresa Swint', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BD-11620', 'Brian DeCherney', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CM-12160', 'Charles McCrossin', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SN-20560', 'Skye Norling', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EH-14005', 'Erica Hernandez', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('FO-14305', 'Frank Olsen', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MS-17710', 'Maurice Satty', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CC-12100', 'Chad Cunningham', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DW-13540', 'Don Weiss', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BT-11395', 'Bill Tyler', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CY-12745', 'Craig Yedwab', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BT-11485', 'Brad Thomas', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PS-19045', 'Penelope Sewall', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PV-18985', 'Paul Van Hugh', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NM-18520', 'Neoma Murray', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DL-13495', 'Dionis Lloyd', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CS-12355', 'Christine Sundaresam', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('FH-14275', 'Frank Hawley', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NC-18340', 'Nat Carroll', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AA-10315', 'Alex Avila', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LT-16765', 'Larry Tron', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AP-10720', 'Anne Pryor', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PM-18940', 'Paul MacIntyre', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AT-10435', 'Alyssa Tate', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CA-12055', 'Cathy Armstrong', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HR-14830', 'Harold Ryan', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BT-11530', 'Bradley Talbott', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LH-16750', 'Larry Hughes', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SW-20755', 'Steven Ward', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SP-20620', 'Stefania Perrino', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BF-11170', 'Ben Ferrer', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KT-16480', 'Kean Thornton', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BG-11695', 'Brooke Gillingham', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GM-14680', 'Greg Matthias', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EJ-14155', 'Eva Jacobs', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NP-18700', 'Nora Preis', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MH-18115', 'Mick Hernandez', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JR-15700', 'Jocasta Rupert', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SM-20950', 'Suzanne McNair', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CC-12220', 'Chris Cortes', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PF-19225', 'Phillip Flathmann', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DC-12850', 'Dan Campbell', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BD-11770', 'Bryan Davis', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GM-14500', 'Gene McClure', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TB-21355', 'Todd Boyes', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JH-16180', 'Justin Hirsh', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EB-13975', 'Erica Bern', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('QJ-19255', 'Quincy Jones', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TC-21535', 'Tracy Collins', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CS-12460', 'Chuck Sachs', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HG-14965', 'Henry Goldwyn', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LW-16825', 'Laurel Workman', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MC-17575', 'Matt Collins', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LP-17095', 'Liz Preis', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EB-14170', 'Evan Bailliet', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GZ-14545', 'George Zrebassa', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CP-12085', 'Cathy Prescott', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('FG-14260', 'Frank Gastineau', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LD-17005', 'Lisa DeCherney', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AB-10255', 'Alejandro Ballentine', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MN-17935', 'Michael Nguyen', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JR-15670', 'Jim Radford', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JF-15190', 'Jamie Frazer', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CM-12115', 'Chad McGuire', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AS-10045', 'Aaron Smayling', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BP-11290', 'Beth Paige', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ND-18370', 'Natalie DeCherney', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LB-16735', 'Larry Blacks', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KT-16465', 'Kean Takahito', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HM-14860', 'Harry Marie', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AB-10600', 'Ann Blume', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SZ-20035', 'Sam Zeldin', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MG-17890', 'Michael Granlund', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JK-16120', 'Julie Kriz', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PP-18955', 'Paul Prost', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('YS-21880', 'Yana Sorensen', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KM-16375', 'Katherine Murray', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AB-10105', 'Adrian Barton', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HA-14905', 'Helen Abelman', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BT-11305', 'Beth Thompson', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SV-20815', 'Stuart Van', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RW-19540', 'Rick Wilson', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DK-12835', 'Damala Kotsonis', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ST-20530', 'Shui Tom', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MM-17920', 'Michael Moore', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PW-19030', 'Pauline Webber', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20440', 'Shaun Chance', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TS-21085', 'Thais Sissman', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MC-17425', 'Mark Cousins', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ME-17320', 'Maria Etezadi', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NH-18610', 'Nicole Hansen', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MB-18085', 'Mick Brown', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KD-16495', 'Keith Dawkins', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KN-16390', 'Katherine Nockton', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NP-18685', 'Nora Pelletier', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CS-12505', 'Cindy Stewart', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MS-17770', 'Maxwell Schwartz', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CM-12655', 'Corinna Mitchell', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('Co-12640', 'Corey-Lock', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TS-21370', 'Todd Sumrall', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JW-15220', 'Jane Waco', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JD-15790', 'John Dryer', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PC-19000', 'Pauline Chand', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AR-10540', 'Andy Reiter', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AI-10855', 'Arianne Irving', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TB-21400', 'Tom Boeckenhauer', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PL-18925', 'Paul Lucas', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GH-14425', 'Gary Hwang', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MP-18175', 'Mike Pelletier', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JM-15655', 'Jim Mitchum', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CL-11890', 'Carl Ludwig', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DB-13270', 'Deborah Brumfield', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('IG-15085', 'Ivan Gibson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BO-11425', 'Bobby Odegard', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AB-10150', 'Aimee Bixby', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JW-16075', 'Julia West', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EB-13750', 'Edward Becker', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SG-20470', 'Sheri Gordon', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CM-12190', 'Charlotte Melton', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AW-10840', 'Anthony Witt', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MC-18100', 'Mick Crebagga', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TT-21460', 'Tonja Turnell', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('VG-21805', 'Vivek Grady', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MY-18295', 'Muhammed Yedwab', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RD-19480', 'Rick Duston', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DP-13390', 'Dennis Pardue', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ML-17395', 'Marina Lichtenstein', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JC-15385', 'Jenna Caffey', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JG-15160', 'James Galang', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MC-17275', 'Marc Crier', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NW-18400', 'Natalie Webber', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TB-21280', 'Toby Braunhardt', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BS-11380', 'Bill Stewart', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HH-15010', 'Hilary Holden', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CD-12280', 'Christina DeMoss', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TH-21100', 'Thea Hendricks', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MM-18055', 'Michelle Moray', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NS-18505', 'Neola Schneider', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RB-19645', 'Robert Barroso', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SW-20455', 'Shaun Weien', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EB-13930', 'Eric Barreto', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PS-18760', 'Pamela Stobb', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HF-14995', 'Herbert Flentye', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HZ-14950', 'Henia Zydlo', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CD-12790', 'Cynthia Delaney', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JK-15205', 'Jamie Kunitz', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('FM-14215', 'Filia McAdams', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ED-13885', 'Emily Ducich', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DA-13450', 'Dianna Arnett', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JW-15955', 'Joni Wasserman', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RM-19375', 'Raymond Messe', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ML-17755', 'Max Ludwig', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CC-12685', 'Craig Carroll', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JE-15610', 'Jim Epp', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RP-19855', 'Roy Phan', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TB-21175', 'Thomas Boland', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BE-11455', 'Brad Eason', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JF-15565', 'Jill Fjeld', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PB-19210', 'Phillip Breyer', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BT-11680', 'Brian Thompson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JL-15235', 'Janet Lee', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CH-12070', 'Cathy Hwang', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ND-18460', 'Neil Ducich', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BF-10975', 'Barbara Fisher', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KH-16330', 'Katharine Harms', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GW-14605', 'Giulietta Weimer', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NC-18625', 'Noah Childs', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ME-18010', 'Michelle Ellison', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BP-11230', 'Benjamin Patterson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JC-15775', 'John Castell', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AS-10090', 'Adam Shillingsburg', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AC-10450', 'Amy Cox', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MD-17860', 'Michael Dominguez', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DB-13660', 'Duane Benoit', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EH-13990', 'Erica Hackney', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EH-13765', 'Edward Hooks', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20230', 'Scot Coram', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JE-15715', 'Joe Elijah', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AC-10615', 'Ann Chong', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JD-16015', 'Joy Daniels', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CB-12415', 'Christy Brittain', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JS-16030', 'Joy Smith', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LW-17215', 'Luke Weiss', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20800', 'Stuart Calhoun', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AM-10705', 'Anne McFarland', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RH-19510', 'Rick Huthwaite', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CT-11995', 'Carol Triggs', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MC-17590', 'Matt Collister', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CC-12610', 'Corey Catlett', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KA-16525', 'Kelly Andreada', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TC-20980', 'Tamara Chand', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BF-11080', 'Bart Folk', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MM-17260', 'Magdelene Morse', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AH-10120', 'Adrian Hane', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BW-11200', 'Ben Wallace', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SW-20245', 'Scot Wooten', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BS-11665', 'Brian Stugart', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RF-19345', 'Randy Ferguson', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('WB-21850', 'William Brown', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TB-21625', 'Trudy Brown', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AF-10870', 'Art Ferguson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RB-19435', 'Richard Bierner', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KF-16285', 'Karen Ferguson', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JH-15820', 'John Huston', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('IL-15100', 'Ivan Liston', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PB-18805', 'Patrick Bzostek', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RH-19600', 'Rob Haberlin', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AW-10930', 'Arthur Wiediger', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ML-17410', 'Maris LaWare', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DB-13555', 'Dorothy Badders', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MH-17620', 'Matt Hagelstein', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DK-13375', 'Dennis Kane', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BT-11440', 'Bobby Trafton', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DB-13405', 'Denny Blanton', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TG-21310', 'Toby Gnade', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BF-11005', 'Barry Franz', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JM-16195', 'Justin MacKendrick', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MZ-17335', 'Maria Zettner', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MW-18220', 'Mitch Webber', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MV-17485', 'Mark Van Huff', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SM-20320', 'Sean Miller', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TP-21415', 'Tom Prescott', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JK-15625', 'Jim Karlsson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PJ-18835', 'Patrick Jones', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RS-19420', 'Ricardo Sperren', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SV-20935', 'Susan Vittorini', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BC-11125', 'Becky Castell', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EM-13825', 'Elizabeth Moffitt', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BM-11575', 'Brendan Murry', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KN-16705', 'Kristina Nunn', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KW-16570', 'Kelly Williams', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20260', 'Scott Cohen', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CV-12295', 'Christina VanderZanden', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SG-20605', 'Speros Goranitis', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TM-21010', 'Tamara Manning', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EM-13810', 'Eleni McCrary', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ML-18040', 'Michelle Lonsdale', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CR-12580', 'Clay Rozendal', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AZ-10750', 'Annie Zypern', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PW-19240', 'Pierre Wener', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20380', 'Shahid Collister', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CM-11935', 'Carlos Meador', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GM-14695', 'Greg Maxwell', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TB-21250', 'Tim Brockman', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JM-15865', 'John Murray', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20575', 'Sonia Cooley', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LS-17200', 'Luke Schmidt', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RR-19315', 'Ralph Ritter', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DB-12910', 'Daniel Byrd', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TT-21220', 'Thomas Thornton', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LO-17170', 'Lori Olson', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KD-16615', 'Ken Dana', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NB-18580', 'Nicole Brennan', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BD-11635', 'Brian Derr', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CM-12235', 'Chris McAfee', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EN-13780', 'Edward Nazzal', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KN-16450', 'Kean Nguyen', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BO-11350', 'Bill Overfelt', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AG-10300', 'Aleksandra Gannaway', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MC-17635', 'Matthew Clasen', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TA-21385', 'Tom Ashbrook', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JF-15295', 'Jason Fortune-', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TT-21265', 'Tim Taslimi', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SB-20170', 'Sarah Bern', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CL-12700', 'Craig Leslie', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HG-15025', 'Hunter Glantz', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NL-18310', 'Nancy Lomonaco', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RR-19525', 'Rick Reed', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TC-21295', 'Toby Carlisle', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SV-20785', 'Stewart Visinsky', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BE-11410', 'Bobby Elias', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20680', 'Steve Carroll', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DF-13135', 'David Flashing', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('FH-14350', 'Fred Harton', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MS-17530', 'MaryBeth Skach', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RH-19555', 'Ritsa Hightower', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GA-14515', 'George Ashbrook', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JP-16135', 'Julie Prescott', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('Dp-13240', 'Dean percer', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MO-17950', 'Michael Oakman', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DL-13330', 'Denise Leinenbach', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MH-18025', 'Michelle Huthwaite', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DR-12940', 'Daniel Raglin', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DM-13015', 'Darrin Martin', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CA-11965', 'Carol Adams', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AC-10660', 'Anna Chung', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DM-13345', 'Denise Monton', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('VF-21715', 'Vicky Freymann', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CC-12370', 'Christopher Conant', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BF-11275', 'Beth Fritzler', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HG-14845', 'Harry Greene', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BP-11155', 'Becky Pak', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EM-14140', 'Eugene Moren', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MA-17995', 'Michelle Arnett', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AY-10555', 'Andy Yotov', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GB-14575', 'Giulietta Baptist', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JB-16045', 'Julia Barnett', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MG-17875', 'Michael Grace', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SR-20425', 'Sharelle Roach', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JB-16000', 'Joy Bell-', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DM-12955', 'Dario Medina', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TC-21475', 'Tony Chapman', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SW-20350', 'Sean Wendt', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RE-19450', 'Richard Eichhorn', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BF-11215', 'Benjamin Farhat', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KB-16405', 'Katrina Bavinger', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JG-15310', 'Jason Gross', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EC-14050', 'Erin Creighton', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EB-14110', 'Eugene Barchas', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JP-15460', 'Jennifer Patt', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CS-11845', 'Cari Sayre', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GH-14410', 'Gary Hansen', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PT-19090', 'Pete Takahito', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JL-15130', 'Jack Lebron', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AH-10030', 'Aaron Hawkins', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CC-12475', 'Cindy Chapman', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DW-13195', 'David Wiener', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SJ-20215', 'Sarah Jordon', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BG-11740', 'Bruce Geld', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LB-16795', 'Laurel Beltran', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CM-11815', 'Candace McMahon', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EH-14185', 'Evan Henry', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TS-21505', 'Tony Sayre', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PR-18880', 'Patrick Ryan', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LC-17050', 'Liz Carlisle', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CS-12490', 'Cindy Schnelling', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DH-13075', 'Dave Hallsten', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JO-15145', 'Jack O''Briant', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AH-10690', 'Anna Häberlin', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HJ-14875', 'Heather Jas', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MH-17455', 'Mark Hamilton', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RD-19930', 'Russell D''Ascenzo', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20020', 'Sam Craven', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SU-20665', 'Stephanie Ulpright', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('FC-14335', 'Fred Chung', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RB-19330', 'Randy Bradley', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NC-18535', 'Nick Crebassa', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DB-12970', 'Darren Budd', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MF-17665', 'Maureen Fritzler', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RM-19750', 'Roland Murray', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('VM-21835', 'Vivian Mathis', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EJ-13720', 'Ed Jacobs', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NC-18415', 'Nathan Cano', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LS-17230', 'Lycoris Saunders', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KE-16420', 'Katrina Edelman', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DH-13675', 'Duane Huffman', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('PF-19120', 'Peter Fuller', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('VT-21700', 'Valerie Takahito', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MG-17695', 'Maureen Gnade', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SP-20920', 'Susan Pistek', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CS-12175', 'Charles Sheldon', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DK-12895', 'Dana Kaydos', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KM-16660', 'Khloe Miller', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AA-10645', 'Anna Andreadi', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DD-13570', 'Dorothy Dickinson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AH-10465', 'Amy Hunt', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TP-21565', 'Tracy Poddar', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EK-13795', 'Eileen Kiefer', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CR-12820', 'Cyra Reiten', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SG-20890', 'Susan Gilcrest', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AH-10585', 'Angele Hood', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NF-18475', 'Neil Französisch', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BS-11365', 'Bill Shonely', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SH-20635', 'Stefanie Holloman', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RD-19720', 'Roger Demir', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AG-10330', 'Alex Grayson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('GR-14560', 'Georgia Rosenberg', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('VS-21820', 'Vivek Sundaresam', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TM-21490', 'Tony Molinari', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TS-21430', 'Tom Stivers', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DB-13360', 'Dennis Bolton', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('NR-18550', 'Nick Radford', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CS-11860', 'Cari Schnelling', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MF-18250', 'Monica Federle', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LW-17125', 'Liz Willingham', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AR-10345', 'Alex Russell', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('KS-16300', 'Karen Seio', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AB-10015', 'Aaron Bergman', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LR-17035', 'Lisa Ryan', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SS-20410', 'Shahid Shariari', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JM-15580', 'Jill Matthias', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JK-15325', 'Jason Klamczynski', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DM-13525', 'Don Miller', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('ML-18265', 'Muhammed Lee', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MH-17290', 'Marc Harrigan', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('FC-14245', 'Frank Carlisle', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TH-21115', 'Thea Hudgings', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('JK-16090', 'Juliana Krohn', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SB-20185', 'Sarah Brown', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BG-11035', 'Barry Gonzalez', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BW-11065', 'Barry Weirich', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MG-18205', 'Mitch Gastineau', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('DO-13645', 'Doug O''Connell', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BP-11050', 'Barry Pond', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TS-21655', 'Trudy Schmidt', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('EM-14200', 'Evan Minnotte', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AO-10810', 'Anthony O''Donnell', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('MH-17440', 'Mark Haberlin', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SS-20515', 'Shirley Schmidt', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LD-16855', 'Lela Donovan', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('VP-21760', 'Victoria Pisteka', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('TC-21145', 'Theresa Coyne', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('IM-15055', 'Ionia McGrath', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('AR-10570', 'Anemone Ratner', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CM-12715', 'Craig Molinari', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('FW-14395', 'Fred Wasserman', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('LC-16960', 'Lindsay Castell', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HE-14800', 'Harold Engle', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('BD-11560', 'Brendan Dodson', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('HD-14785', 'Harold Dahlen', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('CJ-11875', 'Carl Jackson', 'Corporate');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RS-19870', 'Roy Skaria', 'Home Office');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SC-20845', 'Sung Chung', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('RE-19405', 'Ricardo Emerson', 'Consumer');
INSERT IGNORE INTO customers (customer_id, customer_name, segment) VALUES ('SM-20905', 'Susan MacKendrick', 'Consumer');
